IF
  Global("VA#ShardDestroyed","GLOBAL",2)
  Global("VA#TowerDoor","GLOBAL",0)
THEN
    RESPONSE #100
             SetGlobal("VA#TowerDoor","GLOBAL",1)
             CloseDoor("Towerdoor")
             Lock("Towerdoor")
             TriggerActivation("Tran0002",FALSE)
END

IF
  Dead("VA#ZOM01")
  Dead("VA#ZOM02")
  Dead("VA#ZOM03")
  Global("VA#ZombiesDead","GLOBAL",0)
THEN
    RESPONSE #100
             SetGlobal("VA#ZombiesDead","GLOBAL",1)
             AddJournalEntry(@17,QUEST)
END
