IF
  Clicked([ANYONE])
  Range(LastTrigger,10)
THEN
  RESPONSE #100
    SetGlobal("RZNotAllowTeleport","GLOBAL",0)
    StartCutSceneMode()
    Wait(1)
    FadeToColor([45.0],0)
    Wait(2)
    RestorePartyLocations()
    MultiPlayerSync()
    FadeFromColor([45.0],0)
    Wait(2)
    EndCutSceneMode()
END

IF
  Clicked([ANYONE])
  !Range(LastTrigger,10)
THEN
  RESPONSE #100
    DisplayString(Myself,14702)  // ~You are too far away to use that.~
END